version: '3.2'
services:
  api:
    container_name: "${APP_NAME}-nodejs"
    build:
      context: .
      dockerfile: Dockerfile
    command: sh ./docker-start.sh
    environment:
      - NODE_ENV=dev
    volumes:
      - .:/home/app
      - /home/app/node_modules
    ports:
      - "3333:3333"
    networks:
      - default
    depends_on:
      - postgres

  postgres:
    container_name: "${APP_NAME}-postgres"
    image: postgres:10.4-alpine
    volumes:
      - "./data/:/var/lib/postgres"
      - "./dump/:/docker-entrypoint-initdb.d"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: edgard
      POSTGRES_PASSWORD: edgard
      POSTGRES_DB: edgard

networks:
  default:
    driver: bridge
